### ISSUE TITLE
build_release action - deprecated node12

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx-sdcard-sounds#94]
`.github/workflows/build_release.yml`

Uses `marvinpinto/action-automatic-releases` which is dependent on node12, which is now depreciated. Need to swap it out for another upload/release action. It is also responsible the two `set-output` warnings, which will also stop working soon.

**Comment by pfeerick** [comment]
One possibility is to switch to https://github.com/tj-actions/git-cliff for the changelog, and https://github.com/ncipollo/release-action for the upload action. Both are actively maintained actions. 


example stub combining the two
```
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for changelog

      - name: Generate changelog with git-cliff
        uses: tj-actions/git-cliff@v1
        with:
          args: --latest --strip all
          output: "CHANGELOG.md"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "CHANGELOG.md"
          draft: false
          prerelease: false
```
